import os

from sqlalchemy.ext.asyncio import AsyncSession, create_async_engine

env = os.environ

TELEGRAM_TOKEN = env['TOKEN']
SUBSCRIPTION_PRICE = int(env['SUBSCRIPTION_PRICE'])


RABBITMQ_URL = f"amqp://{env['RABBITMQ_USERNAME']}:{env['RABBITMQ_PASSWORD']}@{env['RABBITMQ_HOST']}/"
QUEUE_NAME = env["RABBITMQ_QUEUE"]


HOSTING_URL = f"http://{env['HOSTING_HOST']}:{env['HOSTING_PORT']}"

SECRET_KEY = env['SECRET_KEY']
ALGORITHM = env['ACCESS_TOKEN_ALGORITHM']
ACCESS_TOKEN_EXPIRE_MINUTES = int(env['ACCESS_TOKEN_EXPIRE_MINUTES'])


POSTGRESQL_USERNAME = env['POSTGRESQL_USERNAME']
POSTGRESQL_PASSWORD = env['POSTGRESQL_PASSWORD']
POSTGRESQL_DATABASE = env['POSTGRESQL_DATABASE']
POSTGRESQL_HOST = env['POSTGRESQL_HOST']
POSTGRESQL_PORT = env['POSTGRESQL_PORT']
DATABASE_URL = f"postgresql+asyncpg://{POSTGRESQL_USERNAME}:{POSTGRESQL_PASSWORD}@{POSTGRESQL_HOST}:{POSTGRESQL_PORT}/{POSTGRESQL_DATABASE}"

engine = create_async_engine(DATABASE_URL)
session: AsyncSession = AsyncSession(engine)
